# travis-ci test main source and push to mirrors

language: bash
sudo: enabled
os: linux
dist: focal

before_install:
  - sudo apt-get update

arch:
  - amd64
#  - arm64
#  - armhf

install:
  - sudo git clone https://github.com/casjay-dotfiles/scripts "/usr/local/share/CasjaysDev/scripts"
  - sudo /usr/local/share/CasjaysDev/scripts/install.sh
  - sudo rm -Rf /usr/local/share/CasjaysDev/scripts/.git
  - sudo bash -c "$(curl -LSs https://github.com/dfmgr/installer/raw/master/install.sh)" || exit 1
  - sudo dfmgr install git misc bash
  - sudo ./tests/travis-ci.sh

#services:
#  - docker

#before_install:
#  - docker pull archlinux
#  - docker pull centos
#  - docker pull debian
#  - docker pull fedora
#  - docker pull ubuntu

#script:
#  - docker run --rm -v $(pwd):/scripts -it archlinux /bin/bash -c /scripts/tests/docker-pacman.sh
#  - docker run --rm -v $(pwd):/scripts -it centos /bin/bash -c /scripts/tests/docker-yum.sh
#  - docker run --rm -v $(pwd):/scripts -it fedora /bin/bash -c /scripts/tests/docker-dnf.sh
#  - docker run --rm -v $(pwd):/scripts -it debian /bin/bash -c /scripts/tests/docker-apt.sh
#  - docker run --rm -v $(pwd):/scripts -it ubuntu /bin/bash -c /scripts/tests/docker-apt.sh

notifications:
  email:
    on_failure: never
    on_success: never
